const steps=['TRACKED','DELIVERED','RETURN_WAIT','VALIDATED','RELEASED'];
const labels=['Ghi nhận đơn','Giao hàng thành công','Chờ hết thời hạn đổi trả','Shopee chốt hoa hồng','Tiền về ví'];
function order(id,name,kind,amount,asset,day){
 const released=kind==='released';const valid=kind==='validated'||released;
 return {order_sn:id,name,image:asset,purchase_time:`2026-10-${day}T03:10:00Z`,status:kind==='rejected'?'REJECTED':valid?'VALIDATED':'PENDING',est_cashback:kind==='pending'?amount:null,cashback_amount:kind==='pending'?null:kind==='rejected'?0:amount,financial_review_status:null,timeline:steps.map((code,i)=>({code,label:labels[i],done:i===0||valid&&i<4||released&&i===4,at:i===0?`2026-10-${day}T08:15:00Z`:i===3&&valid?'2026-10-06T08:15:00Z':i===4&&released?'2026-10-07T02:30:00Z':null,...(i===1||i===2?{note:'Shopee không công bố thời gian cụ thể'}:{}),...(i===3&&kind==='rejected'?{reason:'Đơn bị hủy trước khi giao — không tính hoa hồng'}:{})}))};
}
export function createFixture(scenario='returning'){
 const s={user:{id:'demo-lan',display_name:'Lan',email:'lan@example.test',invite_code:'LANABC2345',signedIn:true},settings:{min_withdraw:50000,support:{zalo_oa:'',hotline:''},payment_methods:['BANK','MOMO']},wallet:{pendingOrders:39000,pendingRelease:59000,available:156400,withdrawing:0,withdrawn:1250000,updated_at:'2026-10-07T03:30:00Z'},orders:[order('SP1005','Bình giữ nhiệt 500 ml · màu kem','pending',27000,'bottle','06'),order('SP1004','Túi vải đựng đồ đi làm · màu tự nhiên','pending',12000,'bag','05'),order('SP1003','Tai nghe không dây · màu trắng','validated',54000,'headphones','03'),order('SP1002','Cốc gốm men mờ · 350 ml','validated',5000,'mug','02'),order('SP1001','Đèn bàn đọc sách · ánh sáng ấm','released',42900,'lamp','01'),order('SP1000','Bình giữ nhiệt 500 ml','rejected',0,'bottle','01')],links:[{id:'L1',short_link:'https://s.shopee.vn/demo',name:'Bình giữ nhiệt 500 ml · màu kem',price:249000,est_cashback:57500,base_cashback:50000,rank_bonus:7500,rank_bonus_pct:15,bonus_rank:'VANG',image:'bottle',created_at:'2026-10-06T03:00:00Z'}],ledger:[{id:'e1',order_sn:'SP1001',type:'PAYOUT',delta:39000,note:'Hoàn tiền đơn #SP1001',date:'2026-10-07T02:30:00Z',balance_after:139000},{id:'e2',order_sn:'SP1001',type:'BONUS_RANK',delta:3900,note:'Thưởng hạng — đơn #SP1001',date:'2026-10-07T02:30:00Z',balance_after:142900},{id:'e3',source_name:'Mai',type:'INVITE_EARNING',delta:13500,note:'Tiền mời bạn — đơn của Mai',date:'2026-10-07T03:00:00Z',balance_after:156400}],withdrawals:[{id:'W0',amount:150000,method:'BANK',account_masked:'••••4821',status:'PAID',note:null,created_at:'2026-09-20T02:00:00Z',paid_at:'2026-09-22T03:00:00Z'}],payoutAccount:{id:'demo-default',method:'BANK',status:'VERIFIED',account_masked:{bank_code:'VCB',account_number:'••••4821',account_holder:'NGUYEN THI LAN'},fingerprint:'demo-default',verification_note:null,updated_at:'2026-10-01T03:00:00Z',history:[]},rank:{rank:'BAC',bonus_rank:'VANG',bonus_pct:15,grace_until:'2026-10-26T00:00:00Z',period:{month:'2026-10',commission:1480000},progress_to_next:{need_amount:520000,next_rank:'VANG'},thresholds:{BAC:500000,VANG:2000000,KIMCUONG:5000000}},invite:{code:'LANABC2345',url:'https://example.test/i/LANABC2345',count:12,active_count:7,earned_this_month:13500,rate_pct:10,claimed:false,earnings:[{id:'e3',amount:13500,referred_name:'Mai',product_name:'Đồ dùng gia đình',date:'2026-10-07T03:00:00Z'}]},device:{supported:true,permission:'default',enabled:false},network:{online:true},scenario,snapshot:true};
 s.payoutAccounts=[{...s.payoutAccount}];s.activePayoutId=s.payoutAccount.id;
 const components=[[23478.26,3521.74],[10434.78,1565.22],[46956.52,7043.48],[4347.83,652.17]];
 s.orders.slice(0,4).forEach((o,i)=>Object.assign(o,{base_cashback:components[i][0],rank_bonus:components[i][1],rank_bonus_pct:15,bonus_rank:'VANG'}));
 s.orders[4]={...s.orders[4],base_cashback:39000,rank_bonus:3900};
 if(scenario==='long-names'){s.orders[0].name='Bình giữ nhiệt inox 500 ml màu kem, nắp chống tràn, giữ nóng và lạnh, dùng cho mẹ và bé khi đi làm hoặc đi du lịch — phiên bản đầy đủ tên sản phẩm rất dài';s.orders[1].name='Túi vải đựng đồ đi làm và đồ cho em bé, nhiều ngăn, chất vải tự nhiên, có quai đeo vai điều chỉnh và ngăn phụ tiện dụng';s.orders[2].name='Tai nghe Bluetoothkhôngdâysiêudàikhôngcókhoảngtrắngđểkiểmtrabốtụcchữkhôngbịtràn khỏi hàng đơn';}
 if(scenario==='new'){s.orders=[];s.links=[];s.ledger=[];s.withdrawals=[];s.payoutAccount=null;s.payoutAccounts=[];s.activePayoutId=null;s.wallet={pendingOrders:0,pendingRelease:0,available:0,withdrawing:0,withdrawn:0,updated_at:s.wallet.updated_at};s.rank={...s.rank,rank:'DONG',bonus_rank:'DONG',bonus_pct:5,grace_until:null,period:{month:'2026-10',commission:0},progress_to_next:{need_amount:500000,next_rank:'BAC'}};s.invite={...s.invite,count:0,active_count:0,earned_this_month:0,earnings:[]};}
 if(scenario==='review'){s.orders[4].status='REJECTED';s.orders[4].financial_review_status='REVIEW_REQUIRED';s.orders[4].timeline[3].done=false;s.orders[4].timeline[3].reason='Shopee thay đổi kết quả sau khi tiền đã về ví. Khoản hoàn tiền đang được kiểm tra.';}
 if(scenario==='offline'||scenario==='offline-empty'){s.network.online=false;s.snapshot=scenario!=='offline-empty';}
 if(scenario==='account-pending'){s.payoutAccount.status='PENDING_VERIFICATION';s.payoutAccounts[0].status='PENDING_VERIFICATION';}
 if(scenario==='account-rejected'){s.payoutAccount.status='REJECTED';s.payoutAccount.verification_note='Cần kiểm tra lại tên chủ tài khoản.';s.payoutAccounts[0].status='REJECTED';s.payoutAccounts[0].verification_note=s.payoutAccount.verification_note;}
 if(scenario==='multi-payout'){s.payoutAccounts.push({id:'demo-tcb',method:'BANK',status:'VERIFIED',account_masked:{bank_code:'TCB',account_number:'••••2098',account_holder:'NGUYEN THI LAN'},verification_note:null,updated_at:'2026-10-07T03:00:00Z',history:[]},{id:'demo-momo',method:'MOMO',status:'PENDING_VERIFICATION',account_masked:{momo_phone:'••••6789'},verification_note:null,updated_at:'2026-10-07T03:00:00Z',history:[]});}
 if(scenario==='device-denied')s.device.permission='denied';
 if(scenario==='device-unsupported')s.device.supported=false;
 return s;
}
