import {cashbackBreakdown,walletMovements} from './earnings.mjs?v=10';
import {esc,money,date,icon,art,button,menu,note} from './ui.mjs?v=10';
import {payoutWalletCard} from './payout-card.mjs?v=10';

const pendingPath=rows=>rows.length===1?'/withdrawals/'+esc(rows[0].id):'/withdrawals/pending';
export function moneyOverview(w,pending=[]){return `<section class="quick-wallet" aria-label="Tiền hoàn xem nhanh"><a class="quick-main" href="#/wallet"><div><span class="eyebrow">Có thể rút</span><strong>${money(w.available)}</strong></div><span class="round-arrow" aria-label="Xem ví">${icon('arrow')}</span></a><div class="quick-pending"><a href="#/orders" data-order-filter="PENDING"><span>Đang ghi nhận</span><b>${money(w.pendingOrders)}</b></a><a href="#/orders" data-order-filter="VALIDATED"><span>Chờ về ví</span><b>${money(w.pendingRelease)}</b></a></div>${w.withdrawing>0?`<a href="#${pendingPath(pending)}" class="quick-withdraw">${icon('clock')} Đang rút ${money(w.withdrawing)}${pending.length>1?' · '+pending.length+' yêu cầu':''} ${icon('chevron')}</a>`:''}</section>`;}

function result(l){return `<section class="inline-product" aria-label="Sản phẩm vừa kiểm tra"><div class="sr-only" role="status">Sản phẩm của bạn</div><div class="inline-product-info">${art(l.image)}<div><h2>${esc(l.name)}</h2><p>Giá tham khảo ${money(l.price)}</p></div></div>${cashbackBreakdown(l)}${button('Mở Shopee để mua '+icon('arrow'),'shopee')}<div class="inline-product-actions">${button(icon('copy')+' Sao chép','copy-link','text-button',`data-id="${l.id}"`)}${button(icon('share')+' Chia sẻ','share-link','text-button',`data-id="${l.id}"`)}</div></section>`;}

export function home(s,v){return `<div class="home-v2"><div class="home-primary"><div class="overview-heading"><h1>Tiền hoàn của bạn</h1><a href="#/wallet">Xem ví ${icon('chevron')}</a></div>${moneyOverview(s.wallet,s.withdrawals.filter(x=>x.status==='PENDING'))}<section class="purchase-area"><div class="card paste-card"><form data-form="link" class="link-form"><label class="form-label" for="shop-link">Dán link sản phẩm Shopee</label><div class="input-wrap ${v.error?'invalid':''}">${icon('link')}<input id="shop-link" name="link" type="url" placeholder="https://shopee.vn/…" value="${esc(v.link||'')}" autocomplete="off" aria-describedby="link-hint${v.error?' link-error':''}" ${v.error?'aria-invalid="true"':''}>${v.link||v.result||v.busy||v.error?button(icon('close'),'clear-link','clear-link','type="button" aria-label="Xóa link và đóng kết quả"'):''}${button('Dán','paste','paste','type="button" aria-label="Dán link và xem sản phẩm"')}</div><p id="link-hint" class="sr-only">Tự xem sản phẩm và tiền hoàn.</p>${v.busy?`<div class="link-progress" role="status"><span class="loading-spinner"></span> Đang tìm sản phẩm và mức hoàn…</div>`:''}${v.error?`<div id="link-error" class="inline-error" role="alert">${icon('alert')}<div><p>${esc(v.error)}</p>${v.retryable?button('Thử lại','retry-link','text-button','type="button"'):''}</div></div>`:''}</form>${v.result?result(v.result):''}</div><a class="help-link" href="#/help">${icon('help')} Cách lấy link từ Shopee</a></section></div><aside class="home-aside"><section class="recent-links"><div class="section-head"><h2>Link gần đây</h2><span class="details-text">${s.links.length}</span></div>${s.links.length?`<div class="recent-list">${s.links.slice(0,3).map(l=>`<a class="recent-item" href="#/product/${l.id}">${art(l.image)}<div><h3>${esc(l.name)}</h3><p>Hoàn dự kiến <b>${money(l.est_cashback)}</b></p></div>${icon('chevron')}</a>`).join('')}</div>`:`<p class="details-text">Link đã tạo sẽ được giữ ở đây để bạn dễ tìm lại.</p>`}</section></aside></div>`;}

export function wallet(s){const w=s.wallet,canWithdraw=w.available>=s.settings.min_withdraw,pending=s.withdrawals.filter(x=>x.status==='PENDING');return `<div class="wallet-v2"><div class="overview-heading"><h1>Ví của bạn</h1></div><section class="balance-main"><span class="eyebrow">Có thể rút</span><div class="amount">${money(w.available)}</div>${canWithdraw?`<a class="primary full" href="#/withdraw">Rút tiền ${icon('arrow')}</a>`:`<button class="primary full" disabled aria-describedby="withdraw-minimum">Rút tiền ${icon('arrow')}</button><p class="min-withdraw" id="withdraw-minimum">Có thể rút từ ${money(s.settings.min_withdraw)}.</p>`}</section>${w.withdrawing>0?`<a class="withdraw-progress" href="#${pendingPath(pending)}"><span class="progress-icon">${icon('clock')}</span><div><span>Đang rút</span><strong>${money(w.withdrawing)}</strong><small>${pending.length>1?pending.length+' yêu cầu · xem từng yêu cầu':'Chờ xử lý · xem tiến trình'}</small></div>${icon('chevron')}</a>`:''}<section class="waiting-money" aria-labelledby="waiting-title"><h2 id="waiting-title" class="sr-only">Tiền đang chờ, chưa thể rút</h2><div class="waiting-grid"><a href="#/orders" data-order-filter="PENDING"><span>Đang ghi nhận</span><strong>${money(w.pendingOrders)}</strong></a><a href="#/orders" data-order-filter="VALIDATED"><span>Chờ về ví</span><strong>${money(w.pendingRelease)}</strong></a></div></section>${payoutWalletCard(s.payoutAccount,s.payoutAccounts?.length||0)}${walletMovements(s)}<section class="wallet-manage"><div class="list-menu">${menu('Lịch sử rút tiền',pending.length?'Có yêu cầu đang chờ':'Các lần nhận tiền của bạn','clock','/withdrawals')}</div></section><details class="wallet-summary"><summary>Đã rút & thông tin ví ${icon('chevron')}</summary><div class="summary-content"><div class="summary-row"><span>Đã rút thành công</span><b>${money(w.withdrawn)}</b></div>${w.withdrawing===0?`<div class="summary-row"><span>Đang rút</span><b>${money(0)}</b></div>`:''}<p>“Đã rút” là tổng tiền đã chuyển thành công trước đây, không cộng vào số dư có thể rút.</p><p>Cập nhật ${date(w.updated_at)} · dữ liệu mô phỏng</p><a class="text-button" href="#/ledger">Xem từng khoản cộng, trừ ${icon('arrow')}</a></div></details></div>`;}
