import {cashbackBreakdown,ledgerScreen} from './earnings.mjs?v=20261008-w1';
import {home,wallet} from './overview.mjs?v=20261009-f1';
import {withdrawalHistoryScreen} from './withdraw-history.mjs?v=20261009-f1';
import {rankView} from './rank-view.mjs?v=20261008-ui2-v1';
import {bankOptions,bankName,payoutSavedAccounts} from './payout-card.mjs?v=20261008-c3';
import {esc,money,date,icon,art,button,top,menu,note,status,badge,empty} from './ui.mjs?v=10';
const section=(title,body,link='')=>`<section class="section"><div class="section-head"><h2>${title}</h2>${link}</div>${body}</section>`;
const rankName=r=>({DONG:'Đồng',BAC:'Bạc',VANG:'Vàng',KIMCUONG:'Kim cương'}[r]||'Thành viên');

const dateTime=value=>value?new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Ho_Chi_Minh'}).format(new Date(value)):'';
const shortRequest=id=>String(id).slice(-6).toUpperCase();
const orderState=o=>o.financial_review_status==='REVIEW_REQUIRED'?'REVIEW_REQUIRED':o.status==='REJECTED'?'REJECTED':o.timeline?.some(t=>t.code==='RELEASED'&&t.done)?'RELEASED':o.status;
function orderTimeline(o){
 const rejected=orderState(o)==='REJECTED';const rows=rejected?o.timeline.filter(t=>t.done):o.timeline;
 const current=rejected?-1:rows.findIndex(t=>!t.done);const genericNote='Shopee không công bố thời gian cụ thể';
 const isGeneric=t=>String(t.note||'').trim().replace(/[.!]$/,'')===genericNote;
 const reason=o.timeline.find(t=>t.reason)?.reason||'Đơn chưa đủ điều kiện hoàn tiền.';
 const timingHelp=rows.some(isGeneric)?`<details class="accordion timeline-help"><summary>Về thời gian xử lý ${icon('chevron')}</summary><p>${genericNote}. Các mốc được cập nhật khi có xác nhận.</p></details>`:'';
 return `<ol class="timeline">${rows.map((t,i)=>{const info=[t.at?date(t.at):'',i===current?'Đang chờ':'',t.note&&!isGeneric(t)?esc(t.note):'',t.reason?esc(t.reason):''].filter(Boolean);return `<li class="${t.done?'done':''}"${i===current?' aria-current="step"':''}><span class="timeline-dot">${t.done?icon('check'):icon('clock')}</span><h3>${esc(t.label)}</h3>${info.length?`<p>${info.join('<br>')}</p>`:''}</li>`;}).join('')}${rejected?`<li class="terminal-rejected"><span class="timeline-dot">${icon('close')}</span><h3>Không được hoàn</h3><p>${esc(reason)}</p></li>`:''}</ol>${timingHelp}`;
}
const orderDetails=o=>`${cashbackBreakdown(o,{estimated:o.status==='PENDING'})}${o.financial_review_status==='REVIEW_REQUIRED'?note('Khoản đã ghi có vẫn được giữ trong ví trong lúc kiểm tra.','warning'):''}<h2>Tiến trình hoàn tiền</h2>${orderTimeline(o)}`;
const orderProgress=o=>{
 const state=orderState(o);
 if(state==='REJECTED'||state==='REVIEW_REQUIRED'||!Array.isArray(o.timeline)||!o.timeline.length)return '';
 const done=o.timeline.filter(t=>t.done).length;
 const total=o.timeline.length;
 return `<span class="order-mini-progress" aria-label="${done} trên ${total} bước hoàn tiền"><span class="order-mini-rail" aria-hidden="true">${o.timeline.map((t,i)=>`<i class="${t.done?'done':i===done?'next':''}"></i>`).join('')}</span><span class="order-mini-count" aria-hidden="true">${done}/${total}</span></span>`;
};
const orderVisualStatus=o=>{
 const state=orderState(o);
 const [label,tone]=status(o);
 const symbol=state==='RELEASED'?'check':state==='REJECTED'?'close':state==='REVIEW_REQUIRED'?'alert':'clock';
 return `<span class="order-visual-status order-visual-status--${tone}">${icon(symbol)}<span>${esc(label)}</span></span>`;
};
const row=(o,openOrders=[])=>`<details class="order-disclosure" data-state="${esc(orderState(o))}" data-order-id="${esc(o.order_sn)}"${openOrders.includes(o.order_sn)?' open':''}><summary class="product-row order-row">${art(o.image)}<div class="order-content"><div class="order-top"><h2 class="order-name">${esc(o.name)}</h2>${icon('chevron')}</div><div class="order-meta">${esc(o.order_sn)} · ${date(o.purchase_time)}</div><div class="order-bottom"><div class="order-status-stack">${orderVisualStatus(o)}${orderProgress(o)}</div><div class="order-amount"><b>${money(o.cashback_amount??o.est_cashback)}</b><span>${o.status==='PENDING'?'dự kiến':'tiền hoàn'}</span></div></div></div></summary><div class="order-inline-detail">${orderDetails(o)}</div></details>`;
const account=a=>a?`<div class="account-summary"><div class="account-summary-header">${icon('bank')}<h3>${a.method==='BANK'?esc(bankName(a.account_masked.bank_code)):'MoMo'}</h3>${badge(a.status==='VERIFIED'?'Đã xác minh':a.status==='REJECTED'?'Cần sửa':'Chờ xác minh',a.status==='VERIFIED'?'green':a.status==='REJECTED'?'red':'amber')}</div><strong>${esc(a.account_masked.account_number||a.account_masked.momo_phone)}</strong><p>${esc(a.account_masked.account_holder||'Tài khoản MoMo')}</p>${a.verification_note?`<p>${esc(a.verification_note)}</p>`:''}</div>`:note('Bạn chưa thêm tài khoản nhận tiền.');
const faq=(q,a)=>`<details class="accordion"><summary>${q}${icon('chevron')}</summary><p>${a}</p></details>`;
export function screen(path,s,v={}){
 const w=s.wallet;
 if(path==='/')return home(s,v);
 if(path.startsWith('/product/')){const l=s.links.find(l=>l.id===path.split('/')[2]);if(!l)return empty('Không tìm thấy link');return `${top('Tiền hoàn sản phẩm')}<div class="card product-info">${art(l.image)}<h2>${esc(l.name)}</h2><p class="price">Giá tham khảo ${money(l.price)}</p>${cashbackBreakdown(l)}${button('Mở Shopee để mua '+icon('arrow'),'shopee')}<div class="split-actions">${button(icon('copy')+' Sao chép link','copy-link','secondary',`data-id="${l.id}"`)}${button(icon('share')+' Chia sẻ','share-link','secondary',`data-id="${l.id}"`)}</div></div>`;}
 if(path==='/orders'){const filters=[['ALL','Tất cả'],['PENDING','Đang ghi nhận'],['VALIDATED','Chờ về ví'],['RELEASED','Đã về ví'],['REJECTED','Không được hoàn'],...(s.orders.some(o=>orderState(o)==='REVIEW_REQUIRED')?[['REVIEW_REQUIRED','Đang kiểm tra']]:[])];const f=v.filter||'ALL';const orders=s.orders.filter(o=>f==='ALL'||orderState(o)===f);return `<div class="overview-heading orders-heading"><div><h1>Đơn hàng</h1><p>${orders.length} đơn${f==='ALL'?' · theo dõi tiền hoàn':' · '+esc(filters.find(([k])=>k===f)?.[1]||'Đang lọc')}</p></div><a href="#/help" aria-label="Trợ giúp đơn hàng">${icon('help')}</a></div><div class="filters order-filters" role="group" aria-label="Lọc trạng thái">${filters.map(([k,t])=>button(t,'filter',`chip ${k===f?'active':''}`,`data-filter="${k}" aria-pressed="${k===f}"`)).join('')}</div>${orders.length?`<div class="card order-list">${orders.map(o=>row(o,v.openOrders||[])).join('')}</div>`:s.orders.length?empty('Chưa có đơn ở trạng thái này','Bạn có thể chọn trạng thái khác để xem đơn.',{iconName:'orders',actionLabel:null}):empty('Chưa có đơn hàng','Dán link và mua qua ứng dụng để bắt đầu nhận tiền hoàn.',{iconName:'orders'})}<p class="details-text spaced">Không thấy đơn? <a class="text-button" href="#/help">Xem hướng dẫn</a></p>`;}
 if(path.startsWith('/orders/')){const o=s.orders.find(x=>x.order_sn===path.split('/')[2]);if(!o)return `${top('Chi tiết đơn hàng')}${empty('Không tìm thấy đơn','Đơn có thể chưa được ghi nhận.',{iconName:'orders',actionLabel:'Xem đơn hàng',href:'/orders'})}`;return `${top('Chi tiết đơn hàng',esc(o.order_sn))}<div class="card"><div class="detail-product">${art(o.image)}<div><h2>${esc(o.name)}</h2><p>Đặt ngày ${date(o.purchase_time)}</p></div></div><hr class="divider">${badge(...status(o))}${orderDetails(o)}</div><a class="help-link" href="#/help">${icon('help')} Cần hiểu thêm về tiến trình?</a>`;}
 if(path==='/wallet')return wallet(s);
 if(path==='/ledger')return ledgerScreen(s,v);
 if(path==='/payout')return `${top('Tài khoản nhận tiền','Chọn một tài khoản đã xác minh để nhận tiền rút.')}${payoutSavedAccounts(s)}<a class="primary full spaced" href="#/payout/edit">+ Thêm tài khoản</a><p class="form-hint">Các tài khoản giữ trạng thái riêng. Chỉ tài khoản đang dùng được áp dụng cho yêu cầu rút mới.</p><p class="details-text">Dữ liệu xác minh trong bản mẫu không phải kết quả kiểm tra ngân hàng.</p>`;
 if(path==='/payout/edit'){const method=v.method||'BANK';return `${top('Thông tin nhận tiền','Thêm tài khoản nhận tiền mới. Dùng thông tin mẫu.')}<form class="card" data-form="payout" aria-busy="${Boolean(v.busy)}"><fieldset class="form-fields" ${v.busy?'disabled':''}><legend class="sr-only">Tài khoản nhận tiền</legend><div class="filters">${['BANK','MOMO'].map(m=>button(m==='BANK'?'Ngân hàng':'MoMo','method',`chip ${m===method?'active':''}`,`data-method="${m}" type="button" aria-pressed="${m===method}"`)).join('')}</div>${method==='BANK'?`<div class="form-group"><label class="form-label" for="bank_code">Ngân hàng</label><select class="field" id="bank_code" name="bank_code" required aria-describedby="bank-hint"><option value="">Chọn ngân hàng</option>${bankOptions.map(([code,label])=>`<option value="${code}" ${v.bank_code===code?'selected':''}>${label}</option>`).join('')}</select><p id="bank-hint" class="form-hint">Danh sách mẫu để thử giao diện.</p></div>`:''}${(method==='BANK'?[['account_number','Số tài khoản','0123456789'],['account_holder','Tên chủ tài khoản','NGUYEN THI LAN']]:[['momo_phone','Số điện thoại MoMo','0901234567']]).map(([n,t,p])=>`<div class="form-group"><label class="form-label" for="${n}">${t}</label><input class="field" id="${n}" name="${n}" placeholder="${p}" value="${esc(v[n]||'')}" ${n==='account_number'?'inputmode="numeric" pattern="[0-9]{6,20}" minlength="6" maxlength="20"':n==='momo_phone'?'inputmode="tel" type="tel" pattern="0[0-9]{9}" minlength="10" maxlength="10"':'minlength="2" maxlength="120" autocapitalize="characters"'} required autocomplete="off"></div>`).join('')}${v.error?`<p class="error" role="alert">${esc(v.error)}</p>`:''}<button class="primary full">${v.busy?'Đang lưu…':'Lưu tài khoản'}</button></fieldset><p class="form-hint">Bản mẫu sẽ mô phỏng kiểm tra thành công khi thông tin hợp lệ. Không nhập tài khoản ngân hàng thật.</p></form>`;}
 if(path==='/withdraw'){if(s.payoutAccount?.status!=='VERIFIED')return `${top('Chuẩn bị nhận tiền')}${account(s.payoutAccount)}${note('Cần xác minh tài khoản nhận tiền trước khi rút. Bạn có thể thử trạng thái đã xác minh trong bảng “Thử bản mẫu”.')}<a class="primary full spaced" href="#/payout">Xem tài khoản nhận tiền</a>`;return `${top('Bạn muốn rút bao nhiêu?')}<form class="card" data-form="amount"><p class="amount-label">Có thể rút: <b>${money(w.available)}</b></p><div class="form-group"><label class="form-label" for="amount">Số tiền rút</label><div class="amount-input"><input class="field" id="amount" name="amount" inputmode="numeric" value="${esc(v.amount||'')}" placeholder="50.000" required aria-describedby="amount-hint"><span>₫</span></div>${button('Rút toàn bộ','all','text-button','type="button"')}<p id="amount-hint" class="form-hint">Tối thiểu ${money(s.settings.min_withdraw)}.</p></div>${v.error?`<p class="error" role="alert">${esc(v.error)}</p>`:''}${account(s.payoutAccount)}<button class="primary full spaced">Tiếp tục ${icon('arrow')}</button></form>`;}
 if(path==='/withdraw/review')return `${top('Kiểm tra trước khi gửi')}<div class="card"><p class="amount-label">Số tiền rút</p><div class="amount">${money(v.amount)}</div><hr class="divider">${account(s.payoutAccount)}<dl><div class="summary-row"><dt>Số dư còn lại</dt><dd>${money(w.available-(v.amount||0))}</dd></div><div class="summary-row"><dt>Trạng thái sau khi gửi</dt><dd>Chờ duyệt</dd></div></dl>${note('Số tiền này sẽ chuyển sang “Đang rút”. Nếu yêu cầu bị từ chối, tiền được hoàn lại ví.')}${v.error?`<p class="error" role="alert">${esc(v.error)}</p>`:''}${button(v.busy?'Đang gửi…':'Xác nhận rút tiền','withdraw','primary full spaced',v.busy?'disabled':'')}<a class="help-link" href="#/withdraw">Sửa số tiền</a></div>`;
 if(path.startsWith('/withdraw/result/')){const x=s.withdrawals.find(x=>x.id===path.split('/')[3]);return x?`${top('Yêu cầu rút tiền')}<div class="card center"><div class="success-mark ${x.status==='REJECTED'?'rejected':x.status==='PAID'?'':'warning'}">${icon(x.status==='REJECTED'?'close':x.status==='PAID'?'check':'clock')}</div><h2>${x.status==='PAID'?'Đã chuyển tiền':x.status==='REJECTED'?'Đã hoàn tiền về Ví':'Đã nhận yêu cầu'}</h2><div class="amount spaced">${money(x.amount)}</div>${badge(x.status==='PAID'?'Đã chuyển':x.status==='REJECTED'?'Đã từ chối':'Chờ duyệt',x.status==='PAID'?'green':x.status==='REJECTED'?'red':'amber')}${x.note?'<p class="form-hint">'+esc(x.note)+'</p>':''}<p class="receipt-ref spaced">Yêu cầu ${esc(shortRequest(x.id))}</p><a class="primary full" href="#/withdrawals/${esc(x.id)}">Theo dõi yêu cầu</a><a class="secondary full" href="#/wallet">Về ví</a></div>`:`${top('Yêu cầu rút tiền')}${empty('Không tìm thấy yêu cầu','',{iconName:'wallet',actionLabel:'Về ví',href:'/wallet'})}`;}
 if(path==='/withdrawals'||path==='/withdrawals/pending')return withdrawalHistoryScreen(s,v,{onlyPending:path.endsWith('/pending')});
 if(path.startsWith('/withdrawals/')){const x=s.withdrawals.find(x=>x.id===path.split('/')[2]);if(!x)return `${top('Tiến trình rút tiền')}${empty('Không tìm thấy yêu cầu','',{iconName:'wallet',actionLabel:'Xem lịch sử',href:'/withdrawals'})}`;const paid=x.status==='PAID',rejected=x.status==='REJECTED';return `${top('Tiến trình rút tiền')}<div class="card withdrawal-tracking"><div class="section-head"><span class="amount-label">Số tiền rút</span>${badge(paid?'Đã chuyển':rejected?'Đã hoàn tiền về Ví':'Chờ duyệt',paid?'green':rejected?'red':'amber')}</div><div class="amount">${money(x.amount)}</div><p class="details-text">${x.method==='BANK'?'Ngân hàng':'MoMo'} ${esc(x.account_masked)}</p><p class="receipt-ref">Mã yêu cầu ${esc(x.id)}</p><ol class="timeline"><li class="done"><span class="timeline-dot">${icon('check')}</span><h3>Đã nhận yêu cầu</h3><p>${dateTime(x.created_at)}</p></li><li class="${rejected?'terminal-rejected':paid?'done':''}"><span class="timeline-dot">${icon(rejected?'close':paid?'check':'clock')}</span><h3>${rejected?'Đã hoàn tiền về Ví':paid?'Đã chuyển tiền':'Chờ chuyển tiền'}</h3><p>${paid?dateTime(x.paid_at):rejected?'Tiền hoàn lại Ví sau khi yêu cầu không được chấp nhận.':'Đang chờ duyệt. Tiền đang được giữ trong khoản đang rút.'}</p></li></ol>${x.note?note(esc(x.note),rejected?'warning':''):''}<a class="primary full" href="#/wallet">Về ví</a><a class="text-button" href="#/withdrawals">Lịch sử rút tiền ${icon('chevron')}</a></div>`;}

 
 if(path==='/account')return `<div class="overview-heading"><h1>Tài khoản</h1></div><div class="profile-card"><span class="avatar">${esc(s.user.display_name?.slice(0,1)||'H')}</span><div><h2>${esc(s.user.display_name)}</h2><p>${esc(s.user.email)}</p></div></div><a class="rank-peek" href="#/rank">${icon('rank')}<span>Hạng ${rankName(s.rank.rank)}<small>Quyền lợi ${rankName(s.rank.bonus_rank)}${Number.isFinite(s.rank.bonus_pct)?' · thưởng thêm '+s.rank.bonus_pct+'%':''}</small></span>${icon('chevron')}</a>${section('Tiện ích',`<div class="list-menu">${menu('Mời bạn cùng nhận tiền','Nhận '+s.invite.rate_pct+'% tiền hoàn gốc từ bạn bè','gift','/invite')}${menu('Tài khoản nhận tiền',s.payoutAccount?.status==='VERIFIED'?'Đã xác minh · '+(s.payoutAccount.account_masked.account_number||s.payoutAccount.account_masked.momo_phone):s.payoutAccount?.status==='REJECTED'?'Cần sửa thông tin':s.payoutAccount?'Chờ xác minh':'Chưa thêm tài khoản','bank','/payout')}${menu('Thông báo trên thiết bị',!s.device.supported?'Thiết bị chưa hỗ trợ':s.device.permission==='denied'?'Đang bị chặn':s.device.enabled?'Đang bật':'Đang tắt','bell','/device')}</div>`)}${section('Trợ giúp',`<div class="list-menu">${menu('Hướng dẫn sử dụng','','help','/help')}${menu('Thêm vào màn hình chính','','shop','/install')}</div>`)}${button('Đăng xuất','logout','text-button spaced')}`;
 if(path==='/rank')return rankView(s);
 if(path==='/invite')return `${top('Mua vui hơn, cùng bạn bè','Chia sẻ cách mua có hoàn tiền.')}<div class="card"><h2>Mã mời của bạn</h2><div class="code-box">${esc(s.invite.code)}${button(icon('copy'),'copy-invite','text-button','aria-label="Sao chép mã mời"')}</div>${button(icon('share')+' Chia sẻ lời mời','share-invite')}<p class="form-hint">Nhận ${s.invite.rate_pct}% trên tiền hoàn gốc đủ điều kiện của người bạn trực tiếp mời; không tính trên thưởng hạng và không trừ tiền của bạn bè. Tiền chỉ hiện ở ví sau khi được ghi nhận.</p></div><div class="stats spaced"><div class="stat"><b>${s.invite.count}</b><span>Bạn đã tham gia</span></div><div class="stat"><b>${money(s.invite.earned_this_month)}</b><span>Đã nhận tháng này</span></div></div>${section('Bạn có mã từ người quen?',s.invite.claimed?note('Đã áp dụng mã người mời.','success'):`<form data-form="invite" class="card" aria-busy="${Boolean(v.busy)}"><fieldset class="form-fields" ${v.busy?'disabled':''}><legend class="sr-only">Áp dụng mã giới thiệu</legend><label for="invite-code" class="form-label">Mã giới thiệu</label><input class="field" id="invite-code" name="code" placeholder="Ví dụ mẫu: MAIABC2345" required value="${esc(v.code||'')}">${v.error?`<p class="error" role="alert">${esc(v.error)}</p>`:''}<button class="secondary full spaced" ${v.busy?'disabled':''}>${v.busy?'Đang kiểm tra…':'Áp dụng mã'}</button></fieldset><p class="form-hint">Áp dụng một lần. Quyền lợi tùy điều kiện tại thời điểm mua.</p></form>`)}${section('Tiền mời bạn đã ghi nhận',s.invite.earnings.length?s.invite.earnings.map(e=>`<div class="ledger-row"><span class="ledger-symbol">${icon('gift')}</span><div class="ledger-body"><div class="ledger-top"><span>Từ ${esc(e.referred_name)}</span><b class="positive">+${money(e.amount)}</b></div><p>${date(e.date)} · Đã vào ví</p></div></div>`).join(''):note('Chưa có khoản tiền mời bạn được ghi nhận.'))}`;
 if(path==='/device')return `${top('Thông báo trên thiết bị')}<div class="card"><div class="section-head"><div><h2>Nhận cập nhật</h2><p class="details-text">Về đơn hàng và tiền hoàn</p></div><button class="toggle" role="switch" aria-checked="${s.device.enabled}" aria-label="Nhận thông báo" data-action="toggle"><span class="toggle-track"><span class="toggle-thumb"></span></span></button></div>${note(!s.device.supported?'Thiết bị này chưa hỗ trợ thông báo.':s.device.permission==='denied'?'Trình duyệt đã chặn thông báo. Bạn có thể đổi quyền trong cài đặt của trình duyệt.':'Tùy chọn chỉ áp dụng cho thiết bị bạn đang dùng.')}<p class="form-hint">Bản mẫu chỉ mô phỏng trạng thái, chưa gửi thông báo thật.</p></div>`;
 if(path==='/help')return `${top('Luôn biết bước tiếp theo')}<div class="card"><h2>Mua hàng trong 3 bước</h2><div class="hint-steps">${[['Sao chép link từ Shopee','Mở sản phẩm bạn muốn mua, chọn Chia sẻ rồi Sao chép liên kết.'],['Dán link vào ứng dụng','Dán link để tự xem sản phẩm và mức hoàn dự kiến, sau đó mở Shopee qua link vừa tạo.'],['Đặt hàng và theo dõi','Mua như thường lệ trên Shopee. Vào Đơn hàng để xem trạng thái khi đơn được ghi nhận.']].map(([t,d],i)=>`<div class="hint-step"><span class="step-number">${i+1}</span><div><h3>${t}</h3><p>${d}</p></div></div>`).join('')}</div></div>${section('Câu hỏi thường gặp',`${faq('Tiền hoàn đến từ đâu?','Ứng dụng nhận hoa hồng từ đơn mua đủ điều kiện trên Shopee và chia sẻ lại một phần cho bạn. Tiền hoàn dự kiến có thể thay đổi theo kết quả đối soát.')}${faq('Vì sao mua xong chưa thấy tiền?','Đơn cần được ghi nhận và chờ Shopee xác nhận hoa hồng. Tiền ở trạng thái “Đang ghi nhận” hoặc “Chờ về ví” chưa thể rút. Không có thời gian cố định cho mọi đơn.')}${faq('Tiền nào tôi có thể rút?','Chỉ số tiền “Có thể rút” trong Ví. Tài khoản nhận tiền cần được xác minh, số tiền phải đạt mức tối thiểu. Mỗi lần rút chỉ dùng số dư có thể rút còn lại.')}${faq('Đơn không được hoàn thì sao?','Xem lý do trong chi tiết đơn. Đơn hủy, trả hàng hoặc không đủ điều kiện hoa hồng có thể không được hoàn. Trường hợp thay đổi sau khi đã ghi có sẽ có thông báo kiểm tra riêng.')}${faq('Tôi cần hỗ trợ thêm','Kênh hỗ trợ chưa được cấu hình trong bản mẫu. Phiên bản chính thức cần cung cấp đầu mối hỗ trợ và quy trình tra soát đơn rõ ràng.')}`)}`;
 if(path==='/install')return `${top('Mở nhanh như một ứng dụng')}<div class="card"><h2>Thêm vào màn hình chính</h2>${faq('Trên iPhone · Safari','Mở ứng dụng bằng Safari, chọn nút Chia sẻ, rồi chọn “Thêm vào MH chính”.')}${faq('Trên Android · Chrome','Mở menu ⋮ của Chrome, tìm “Thêm vào màn hình chính” hoặc “Cài đặt ứng dụng” nếu có.')}${note('Đây là bản mẫu giao diện. Manifest, chế độ cài đặt PWA và bộ nhớ ngoại tuyến sẽ được tích hợp khi nối backend.')}</div>`;
 if(path==='/login')return `<div class="center"><div class="login-logo"><span class="brand">${icon('shop')} Hoàn</span></div><h1 class="login-heading">Mua món mình cần.<br>Giữ lại thêm một chút.</h1><p class="details-text">Đăng nhập để theo dõi đơn và tiền hoàn của bạn.</p>${button('<span class="logo-google">G</span> Tiếp tục với Google','login','secondary full spaced')}<p class="small-print">Đăng nhập mô phỏng · không kết nối Google</p></div>`;
 if(path==='/offline')return `${top('Bạn đang ngoại tuyến')}${note('Kết nối lại mạng để cập nhật đơn và thực hiện giao dịch. Dữ liệu cũ chỉ để tham khảo.','warning')}<a class="secondary full spaced" href="#/">Về trang mua hàng</a>`;
 return `${top('Không tìm thấy trang')}${empty('Trang này không còn khả dụng','Bạn có thể trở về trang mua hàng để tiếp tục.',{iconName:'help',actionLabel:'Về trang mua hàng',href:'/'})}`;
}
