const {chromium}=require('playwright-core'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{let p=new URL(req.url,'http://x').pathname;if(p==='/')p='/index.html';const f=path.resolve(root,'.'+p);if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end()}try{res.writeHead(200,{'Content-Type':{'.html':'text/html','.mjs':'text/javascript','.css':'text/css','.ttf':'font/ttf'}[path.extname(f)]||'text/plain'});res.end(fs.readFileSync(f))}catch{res.writeHead(404);res.end()}});
(async()=>{let browser;try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'});
 const ctx=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
 await ctx.grantPermissions(['clipboard-read','clipboard-write'],{origin});const page=await ctx.newPage();const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const goto=route=>page.goto(origin+'/#'+route,{waitUntil:'networkidle'});
 await goto('/withdraw');
 assert.equal(await page.locator('form[data-form=amount]').count(),1,'withdraw form missing');
 await page.locator('#amount').fill('49.999');
 await page.locator('form[data-form=amount] button.primary').click();
 assert.equal(new URL(page.url()).hash,'#/withdraw','sub-minimum withdrawal should not progress');
 assert.ok((await page.locator('main').innerText()).includes('tối thiểu'),'Minimum withdrawal error missing');
 await page.locator('#amount').fill('50.000');
 await page.locator('form[data-form=amount] button.primary').click();
 assert.equal(new URL(page.url()).hash,'#/withdraw/review','valid amount did not reach confirmation');
 assert.ok((await page.locator('main').innerText()).includes('50.000 ₫'));
 await page.locator('[data-action=withdraw]').click();
 await page.waitForURL(/#\/withdraw\/result\//,{timeout:8000});
 const receipt=await page.locator('main').innerText();assert.ok(receipt.includes('Đã nhận yêu cầu'),receipt.slice(0,340));
 console.log('PASS UI withdrawal: rejected 49,999, accepted 50,000, confirms exactly once and shows result');
 await goto('/wallet');
 const wallet1=await page.locator('main').innerText();
 assert.ok(wallet1.includes('106.400 ₫'),'Withdrawn 50k did not leave correct available');
 assert.ok(wallet1.includes('50.000 ₫'),'Pending 50k absent');
 console.log('PASS UI wallet: pending debit and still-withdrawing state shown');
 await page.locator('[data-action=review]').click();
 assert.ok(await page.locator('#review-withdrawal').count(),'Pending withdrawal absent from review');
 await page.locator('[data-action=reject]').click();
 await goto('/wallet');const wallet2=await page.locator('main').innerText();
 assert.ok(wallet2.includes('156.400 ₫'),'Reject did not restore wallet');
 await goto('/ledger');const ledger=await page.locator('main').innerText();
 assert.ok(ledger.includes('Hoàn lại tiền rút'),'Refund ledger item absent');
 console.log('PASS UI rejected withdrawal: refund to wallet and ledger credit');
 await goto('/payout/edit');
 await page.locator('select[name=bank_code]').selectOption('TCB');
 await page.locator('input[name=account_number]').fill('0123456789');
 await page.locator('input[name=account_holder]').fill('NGUYEN VAN A');
 await page.locator('form[data-form=payout] button.primary').click();
 await page.waitForURL(/#\/payout$/,{timeout:8000});
 const manager=await page.locator('main').innerText();
 assert.ok(manager.includes('••••6789'),'Masked bank account missing');
 assert.ok(!manager.includes('0123456789'),'Unmasked bank account visible');
 console.log('PASS UI bank save and automatic demo verification, masked output');
 await goto('/payout/edit');
 await page.locator('[data-action=method][data-method=MOMO]').click();
 await page.locator('input[name=momo_phone]').fill('0901234567');
 await page.locator('form[data-form=payout] button.primary').click();
 await page.waitForURL(/#\/payout$/,{timeout:8000});
 assert.ok((await page.locator('main').innerText()).includes('••••4567'),'MoMo card missing');
 console.log('PASS UI MoMo account save and masked output');
 await goto('/');await page.locator('#shop-link').fill('https://example.com/evil');
 await page.locator('[role=alert].inline-error').waitFor({timeout:7500});
 assert.equal(await page.locator('.inline-product').count(),0,'Invalid link generated product');
 await page.locator('#shop-link').fill('https://shopee.vn/product/123');
 await page.locator('.inline-product').waitFor({timeout:7500});
 const result=await page.locator('.inline-product').innerText();
 assert.ok(result.includes('57.500 ₫'),result);
 console.log('PASS UI link validation: rejects untrusted domain, recovers with correct 57,500 refund');
 await goto('/invite');await page.locator('form[data-form=invite] input[name=code]').fill('LANABC2345');
 await page.locator('form[data-form=invite] button.secondary').click();
 await page.locator('[role=alert]').first().waitFor({timeout:3500});
 console.log('PASS UI invite: self-referral warning');
 assert.deepEqual(errors,[],'Uncaught JavaScript errors');
 console.log('CRITICAL_USER_FLOWS_PASSED');
}catch(e){console.error('CRITICAL_FLOW_FAILURE',e.stack||e);process.exitCode=1}
finally{await browser?.close();await new Promise(r=>server.close(r))}})();